/* =================== DATA LAYER =================== */
/* Edit this file to update your info, skills, projects, experience, and repos. */

const personalInfo = {
  name: "Rey Rameses Jude III S. Macalutas",
  title: "System Developer | Full-Stack Web & Mobile App Developer",
  location: "Malaybalay, Bukidnon, Philippines",
  email: "macalutasreyramesesjudeiii@gmail.com",
  phone: "+63 9977968305, 09940090476",
  github: "https://github.com/rrjmac026",
  githubUsername: "rrjmac026",
  linkedin: "https://linkedin.com/in/rey-rameses-jude-iii-macalutas-751a16405"
};

const skills = [
  {cat:"frontend", name:"React", level:"Advanced", desc:"Component architecture, hooks, and real-time UI state."},
  {cat:"frontend", name:"JavaScript", level:"Advanced", desc:"ES6+, async patterns, browser APIs."},
  {cat:"frontend", name:"TypeScript", level:"Intermediate", desc:"Typed React components and shared interfaces."},
  {cat:"frontend", name:"HTML", level:"Advanced", desc:"Semantic, accessible markup."},
  {cat:"frontend", name:"CSS", level:"Advanced", desc:"Layout systems, animation, responsive design."},
  {cat:"backend", name:"Laravel", level:"Advanced", desc:"Eloquent, multi-tenancy, agile delivery across many client systems."},
  {cat:"backend", name:"PHP", level:"Advanced", desc:"Server-side logic for Laravel applications."},
  {cat:"backend", name:"Node.js", level:"Intermediate", desc:"Express APIs and backend services."},
  {cat:"backend", name:"Express", level:"Intermediate", desc:"REST routing and middleware."},
  {cat:"backend", name:"REST APIs", level:"Advanced", desc:"Designing and consuming resource-oriented APIs."},
  {cat:"backend", name:".NET / C#", level:"Intermediate", desc:"WPF desktop apps with MVVM architecture."},
  {cat:"database", name:"MySQL", level:"Advanced", desc:"Relational schema design for Laravel apps."},
  {cat:"database", name:"PostgreSQL", level:"Intermediate", desc:"Schema design for desktop and web apps via EF Core."},
  {cat:"database", name:"MongoDB", level:"Intermediate", desc:"Document storage for mobile app backends."},
  {cat:"database", name:"Entity Framework Core", level:"Intermediate", desc:"ORM layer for .NET desktop apps."},
  {cat:"mobile", name:"Flutter", level:"Intermediate", desc:"Cross-platform apps with QR/barcode scanning and real-time sync."},
  {cat:"mobile", name:"Android Studio", level:"Intermediate", desc:"Native Android development."},
  {cat:"tools", name:"Git", level:"Frequently Used", desc:"Branching, rebasing, resolving real conflicts."},
  {cat:"tools", name:"GitHub", level:"Frequently Used", desc:"Issue tracking and version control."},
  {cat:"tools", name:"Docker", level:"Familiar", desc:"Containerized deployments for Laravel apps."},
  {cat:"other", name:"Multi-Tenancy", level:"Advanced", desc:"Isolated per-client environments in a shared platform."},
  {cat:"other", name:"MVC / MVVM", level:"Advanced", desc:"Architectural patterns across web and desktop apps."},
  {cat:"other", name:"Video Editing", level:"Familiar", desc:"Content editing outside of software development."},
  {cat:"other", name:"Hardware Troubleshooting", level:"Familiar", desc:"Diagnosing and fixing PC hardware issues."}
];

const projects = [
  {
    id:"dlis",
    title:"DLIS",
    subtitle:"Damulog Legislative Information System",
    description:"A commissioned records-management system for Damulog LGU tracking local government ordinances, delivered as a Windows desktop app and a web app sharing one PostgreSQL database.",
    problem:"Damulog LGU needed a structured, traceable system for recording ordinances, replacing scattered paper files, with no easy way to track amendments, supersessions, or repeals.",
    solution:"Built a Windows desktop app (C#, WPF, .NET 10) and a web app (React, TypeScript, Laravel) sharing one PostgreSQL database, with ordinance amendment/supersession/repeal tracking, status management, and relationship linking between ordinances.",
    result:"A working system used by Damulog LGU with role-based access control, audit logging, full-text search with filters, PDF document attachments, and print-ready reports.",
    technologies:["C#","WPF",".NET 10","React","TypeScript","Laravel","Docker","PostgreSQL"],
    categories:["fullstack","backend","database"],
    github:"https://github.com/rrjmac026/LLOIS",
    demo:"",
    featured:true,
    status:"Completed",
    images: ["images/dlis/dlis-1.png", "images/dlis/dlis-2.png", "images/dlis/dlis-3.png", "images/dlis/dlis-4.png", "images/dlis/dlis-5.png", "images/dlis/dlis-6.png"],
    features:[
      "Ordinance amendment, supersession, and repeal tracking with relationship linking",
      "Role-based access control across desktop and web apps",
      "Full activity audit logging",
      "Full-text search with filters",
      "PDF document attachments",
      "Print-ready reports"
    ],
    challenges:[
      "Keeping the desktop and web apps consistent while sharing one database",
      "Modeling amendment/supersession/repeal relationships between ordinances"
    ],
    solutionsList:[
      "Shared PostgreSQL backend accessed by both the WPF desktop app (EF Core) and the Laravel web app",
      "Explicit relationship model (amends / repeals / supersedes / related_to) between ordinance records"
    ],
    arch:["WPF desktop (C#, .NET 10)","React + TypeScript (web)","Laravel API","PostgreSQL"]
  },
  {
    id:"peo",
    title:"PEO Management System",
    subtitle:"Provincial Engineer's Office internship project",
    description:"A management system built for the Provincial Engineer's Office during a system development internship, recognized with a Certificate of Recognition.",
    problem:"[What problem did this system solve for the office?]",
    solution:"Built with Laravel, Docker, JavaScript, and MySQL. [Add specific features/modules built.]",
    result:"Delivered a working system during the internship, earning a Certificate of Recognition from the Provincial Engineer's Office.",
    technologies:["Laravel","Docker","JavaScript","MySQL","PHP"],
    categories:["fullstack","backend","database"],
    github:"https://github.com/rrjmac026/PEO",
    demo:"",
    featured:true,
    status:"Completed",
    images: ["images/peo/peo-1.png", "images/peo/peo-2.png", "images/peo/peo-3.png", "images/peo/peo-4.png", "images/peo/peo-5.png"],
    features:["[Feature placeholder — what it manages]","[Feature placeholder]"],
    challenges:["[Challenge placeholder]"],
    solutionsList:["[Solution placeholder]"],
    arch:["Laravel (backend)","MySQL","Docker"]
  },
  {
    id:"tcms",
    title:"TCMS",
    subtitle:"Training Center Management System",
    description:"A multi-tenant platform to manage courses, enrollees, trainers, and certifications, with isolated environments per institution.",
    problem:"Training organizations needed a system to manage courses, trainees, trainers, and certifications, each operating in its own isolated environment under one platform.",
    solution:"Built on Laravel with multi-tenancy, managing enrollees, trainers, and certifications per institution.",
    result:"A working multi-tenant platform for managing courses, enrollees, trainers, and certifications with isolated environments per institution.",
    technologies:["Laravel","Multi-Tenancy","MySQL"],
    categories:["fullstack","backend","database"],
    github:"https://github.com/rrjmac026/TCMS",
    demo:"",
    featured:false,
    status:"Completed",
    images: ["images/tcms/tcms-1.png", "images/tcms/tcms-2.png", "images/tcms/tcms-3.png", "images/tcms/tcms-4.png", "images/tcms/tcms-5.png"],
    features:["Multi-tenant course and enrollee management","Trainer management","Certification tracking"],
    challenges:["Keeping tenant data and configuration isolated within one codebase"],
    solutionsList:["Multi-tenancy pattern with isolated per-institution environments"],
    arch:["Laravel (multi-tenant)","MySQL"]
  },
  {
    id:"scms",
    title:"SCMS",
    subtitle:"Student Counseling Management System",
    description:"A web system for managing student counseling sessions, records, referrals, and counselor scheduling within an academic institution.",
    problem:"[What problem did this solve for the institution?]",
    solution:"Built with Laravel, PHP, and MySQL to manage counseling sessions, records, referrals, and scheduling.",
    result:"A working system for managing student counseling sessions, records, referrals, and counselor scheduling.",
    technologies:["Laravel","PHP","MySQL"],
    categories:["fullstack","backend","database"],
    github:"[YOUR_GITHUB_URL]/SCMS",
    demo:"",
    featured:false,
    status:"Completed",
    images: ["images/scms/scms-1.png", "images/scms/scms-2.png", "images/scms/scms-3.png", "images/scms/scms-4.png", "images/scms/scms-5.png", "images/scms/scms-6.png"],
    features:["Counseling session records","Referral tracking","Counselor scheduling"],
    challenges:["[Challenge placeholder]"],
    solutionsList:["[Solution placeholder]"],
    arch:["Laravel","MySQL"]
  },
  {
    id:"gas",
    title:"GAS",
    subtitle:"Gamified Accounting System",
    description:"An interactive accounting learning platform with points, badges, and leaderboards to improve student engagement and comprehension.",
    problem:"[What problem did this solve for accounting students?]",
    solution:"Built with Laravel, MySQL, and JavaScript, adding points, badges, and leaderboards to accounting coursework.",
    result:"An interactive platform that improved student engagement and comprehension through gamification.",
    technologies:["Laravel","MySQL","JavaScript"],
    categories:["fullstack","frontend","backend"],
    github:"[YOUR_GITHUB_URL]/GAS",
    demo:"",
    featured:false,
    status:"Completed",
    images: ["images/gas/gas-1.png", "images/gas/gas-2.png", "images/gas/gas-3.png", "images/gas/gas-4.png", "images/gas/gas-5.png", "images/gas/gas-6.png"],
    features:["Points and badges system","Leaderboards","Gamified learning modules"],
    challenges:["[Challenge placeholder]"],
    solutionsList:["[Solution placeholder]"],
    arch:["Laravel","MySQL"]
  },
  {
    id:"comelec-v1",
    title:"BukSU Comelec Voting System v1",
    subtitle:"Online election system (2025)",
    description:"The first version of BukSU's official online election system for secure digital voting in student government elections, with real-time results and voter authentication.",
    problem:"Manual or ad-hoc election workflows in schools are slow, hard to audit, and error-prone.",
    solution:"Built with Laravel, Docker, PHP, and MySQL, implementing secure digital voting, real-time results, and voter authentication.",
    result:"BukSU's first official online election system for student government elections.",
    technologies:["Laravel","Docker","PHP","MySQL"],
    categories:["fullstack","backend","database"],
    github:"[YOUR_GITHUB_URL]/buksu-comelec-v1",
    demo:"",
    featured:false,
    status:"Completed (2025)",
    features:["Secure digital voting","Real-time results","Voter authentication"],
    challenges:["Preventing duplicate votes while scaling vote counts in real time"],
    solutionsList:["Vote constraints and authentication checks per voter"],
    arch:["Laravel","MySQL"]
  },
  {
    id:"comelec-v2",
    title:"BukSU Comelec Voting System v2",
    subtitle:"Online election system (2026)",
    description:"An upgrade to the election system with improved security protocols, enhanced UI/UX, advanced audit logging, and expanded reporting.",
    problem:"[What limitations of v1 did this version address?]",
    solution:"Built with Laravel, Docker, PHP, and MySQL, adding improved security, better UI/UX, audit logging, and expanded reports.",
    result:"An upgraded, more secure and more auditable version of BukSU's election system.",
    technologies:["Laravel","Docker","PHP","MySQL"],
    categories:["fullstack","backend","database"],
    github:"https://github.com/rrjmac026/buksu_comelec2k26",
    demo:"",
    featured:false,
    status:"Completed (2026)",
    images: ["images/comelec/comelec-1.png", "images/comelec/comelec-2.png"],
    features:["Improved security protocols","Enhanced UI/UX","Advanced audit logging","Expanded reporting"],
    challenges:["Hardening the production environment and protecting vote privacy in seeded data"],
    solutionsList:["Activity/IP logging for auditing","spatie/laravel-backup for scheduled backups"],
    arch:["Laravel","MySQL","Docker"]
  },
  {
    id:"comelec-mobile",
    title:"BukSU Comelec Mobile App",
    subtitle:"Native Android election app",
    description:"A native Android app for BukSU Comelec operations enabling mobile access to election management, voter verification, and live result monitoring.",
    problem:"[What need did the mobile app fill alongside the web voting system?]",
    solution:"Built with Android Studio, Node.js, and Firebase for mobile election management, voter verification, and live results.",
    result:"A native Android app enabling mobile access to election management, voter verification, and live result monitoring.",
    technologies:["Android Studio","Node.js","Firebase"],
    categories:["mobile","backend"],
    github:"[YOUR_GITHUB_URL]/buksu-comelec-mobile",
    demo:"",
    featured:false,
    status:"Completed",
    features:["Election management on mobile","Voter verification","Live result monitoring"],
    challenges:["[Challenge placeholder]"],
    solutionsList:["[Solution placeholder]"],
    arch:["Native Android","Node.js backend","Firebase"]
  },
  {
    id:"dineflow",
    title:"Dineflow",
    subtitle:"Restaurant Management System",
    description:"A multi-tenant platform with menu management, order processing, and table reservations, with isolated environments for each restaurant client.",
    problem:"[What problem did this solve for restaurant clients?]",
    solution:"Built on Laravel with multi-tenancy, covering menu management, order processing, and table reservations per restaurant client.",
    result:"A multi-tenant platform giving each restaurant client an isolated environment for menu, orders, and reservations.",
    technologies:["Laravel","Multi-Tenancy","MySQL"],
    categories:["fullstack","backend","database"],
    github:"[YOUR_GITHUB_URL]/dineflow",
    demo:"",
    featured:false,
    status:"Completed",
    features:["Menu management","Order processing","Table reservations","Per-client isolated environments"],
    challenges:["[Challenge placeholder]"],
    solutionsList:["[Solution placeholder]"],
    arch:["Laravel (multi-tenant)","MySQL"]
  },
  {
    id:"spta",
    title:"SPTA Scanner",
    subtitle:"School Parent-Teacher Association Scanner App",
    description:"A Flutter-based Android app using QR/barcode scanning for automated attendance tracking, with real-time data sync and report generation.",
    problem:"[What problem did this solve for the PTA / school?]",
    solution:"Built with Flutter and Dart for Android, using QR/barcode scanning for automated attendance tracking.",
    result:"An app for automated attendance tracking with real-time data sync and report generation.",
    technologies:["Flutter","Dart","Android"],
    categories:["mobile","frontend"],
    github:"[YOUR_GITHUB_URL]/spta-scanner",
    demo:"",
    featured:false,
    status:"Completed",
    features:["QR/barcode scanning for attendance","Real-time data sync","Report generation"],
    challenges:["[Challenge placeholder]"],
    solutionsList:["[Solution placeholder]"],
    arch:["Flutter UI","Local/cloud sync"]
  }
];

const experience = [
  {year:"2026", role:"Freelance Full-Stack Developer (Commissioned Project)", org:"Damulog LGU, Philippines", desc:"Developed DLIS, a records-management system for tracking local government ordinances, as a Windows desktop app (C#, WPF, .NET 10) and web app (React, TypeScript, Laravel) sharing one PostgreSQL database. Built ordinance amendment/supersession/repeal tracking, role-based access control, audit logging, full-text search, PDF attachments, and print-ready reports. (Jun 2026 – Sep 2026)", tech:["C#","WPF",".NET 10","React","TypeScript","Laravel","PostgreSQL"]},
  {year:"2026", role:"System Developer Intern", org:"Provincial Engineer's Office, Malaybalay City, Bukidnon", desc:"Developed the PEO Management System using Laravel, Docker, JavaScript, and MySQL. Collaborated with office staff to gather requirements and test the system. Received a Certificate of Recognition for the system delivered. (Feb 2026 – May 2026)", tech:["Laravel","Docker","JavaScript","MySQL","PHP"]}
];

const repos = [
  {name:"LLOIS", desc:"WPF desktop app for the DLIS legislative ordinance management system.", lang:"C#", color:"#178600", stars:"—", forks:"—", updated:"Sep 2026"},
  {name:"dlis-web", desc:"Web companion to DLIS, sharing one database with the desktop app.", lang:"TypeScript", color:"#3178c6", stars:"—", forks:"—", updated:"Sep 2026"},
  {name:"buksu_comelec2k26", desc:"BukSU Comelec Voting System v2 (2026) — Laravel election management system.", lang:"PHP", color:"#4F5D95", stars:"—", forks:"—", updated:"—"},
  {name:"TCMS", desc:"Multi-tenant training course management system built with Laravel.", lang:"PHP", color:"#4F5D95", stars:"—", forks:"—", updated:"—"},
  {name:"PEO", desc:"Management system built for the Provincial Engineer's Office during internship.", lang:"PHP", color:"#4F5D95", stars:"—", forks:"—", updated:"—"}
];
